import type { Task } from "@/types/task";

const now = 1_764_720_000_000;

export const seededTasks: Task[] = [
  {
    id: "task-reset-kitchen",
    title: "Reset the kitchen sparkle zone",
    description: "A quick cleanup so tomorrow morning starts calm.",
    emoji: "✨",
    status: "todo",
    assignedTo: "Maya",
    estimateMinutes: 20,
    priority: "high",
    checklist: [
      { id: "c1", text: "Load and start dishwasher", completed: false },
      { id: "c2", text: "Wipe counters", completed: false },
      { id: "c3", text: "Set out tomorrow's coffee mugs", completed: false },
    ],
    createdAt: now - 30_000,
    updatedAt: now - 30_000,
  },
  {
    id: "task-laundry-fold",
    title: "Fold cozy laundry pile",
    description: "Put on a song and make the couch visible again.",
    emoji: "🧺",
    status: "in_progress",
    assignedTo: "Sam",
    estimateMinutes: 15,
    priority: "medium",
    checklist: [
      { id: "c1", text: "Sort towels", completed: true },
      { id: "c2", text: "Fold clothes", completed: false },
      { id: "c3", text: "Deliver stacks to bedrooms", completed: false },
    ],
    createdAt: now - 60_000,
    updatedAt: now - 10_000,
  },
  {
    id: "task-bathroom",
    title: "Bathroom mini refresh",
    description: "Keep it light: mirror, sink, towels.",
    emoji: "🫧",
    status: "backlog",
    assignedTo: "Together",
    estimateMinutes: 10,
    priority: "low",
    checklist: [
      { id: "c1", text: "Wipe mirror", completed: false },
      { id: "c2", text: "Replace hand towel", completed: false },
    ],
    createdAt: now - 90_000,
    updatedAt: now - 90_000,
  },
  {
    id: "task-groceries",
    title: "Plan tiny grocery run",
    description: "Only the staples that make the week easier.",
    emoji: "🍓",
    status: "review",
    assignedTo: "Maya",
    estimateMinutes: 8,
    priority: "medium",
    checklist: [
      { id: "c1", text: "Check fridge staples", completed: true },
      { id: "c2", text: "Add snacks", completed: true },
      { id: "c3", text: "Confirm dinner ingredients", completed: false },
    ],
    createdAt: now - 120_000,
    updatedAt: now - 5_000,
  },
  {
    id: "task-plants",
    title: "Water the plant babies",
    description: "A peaceful lap around the windowsills.",
    emoji: "🌿",
    status: "done",
    assignedTo: "Sam",
    estimateMinutes: 7,
    priority: "low",
    checklist: [
      { id: "c1", text: "Living room plants", completed: true },
      { id: "c2", text: "Bedroom pothos", completed: true },
    ],
    createdAt: now - 180_000,
    updatedAt: now,
  },
];
